### ISSUE TITLE
Function shallow not found

### ISSUE THREAD

**Issue by mhnierhoff** [jangorecki/shinyBTC#1]
When I try to run the app I get the following error message:

``` r
> shiny::runApp()

Listening on http://127.0.0.1:7183
Error in bmerge(i <- shallow(i), x, leftcols, rightcols, io <- haskey(i),  : 
  konnte Funktion "shallow" nicht finden
Error in bmerge(i <- shallow(i), x, leftcols, rightcols, io <- haskey(i),  : 
  konnte Funktion "shallow" nicht finden
```

**Comment by jangorecki** [comment]
Please provide your session info. At the current moment shinyBTC should works on development versions of data.table and Rbitcoin. It should soon works on stable version of those packages as soon as data.table 1.9.6 will be released I will update Rbitcoin.

**Comment by mhnierhoff** [comment]
I solved it by myself. It was indeed an old version of data.table.

Thanks for the quick reply. :)
