### ISSUE TITLE
"object 'base' not found" error from about.Rmd

### ISSUE THREAD

**Issue by datafj** [jangorecki/shinyBTC#2]
Error msg:
 
> Quitting from lines 23-24 (about.Rmd) 
> Error in eval(expr, envir, enclos) : object 'base' not found

It may have been caused by following code:

`getOption("Rbitcoin.api.dict")[!is.na(base), .(market, currency_pair = paste0(base,quote))][,unique(.SD)]`

**Comment by jangorecki** [comment]
Read online how to ask for support. Your report is really bad. Did you even try checking what is the value of option used in that statement? Closing for now, reopen putting proper information in issue report and attempts undertaken to solve it.
